# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

greedy_knapsack_cpp <- function(x, W) {
    .Call(`_advr_06_greedy_knapsack_cpp`, x, W)
}

